version: '3'        
services:
    fluentd:
        image: fluentd:efk
        container_name: fluentd
        build:
            context: ./fluentd
        environment:
            FLUENTD_CONF: fluentd.conf
        volumes:
            - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluentd.conf
        ports:
            - "9880:9880"
            - "24224:24224"
            - "24224:24224/udp"
        networks:
            - efk

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        container_name: kibana
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - "5601:5601"
        networks:
            - efk

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - efk
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data02:/usr/share/elasticsearch/data
        networks:
            - efk
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data03:/usr/share/elasticsearch/data
        networks:
            - efk
networks:
    efk:
     driver: bridge
volumes:
    data01:
    data02:
    data03: